# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-26 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbec', '0003_auto_20181226_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='weight',
            field=models.IntegerField(default=1),
        ),
    ]
