# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-27 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbec', '0005_permission_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='name',
            field=models.CharField(default='', max_length=32, verbose_name='URL_别名'),
            preserve_default=False,
        ),
    ]
