# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-31 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbec', '0006_permission_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
