# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-31 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbec', '0007_auto_20181231_1724'),
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='roles',
            field=models.ManyToManyField(blank=True, to='rbec.Role', verbose_name='y用户拥有的角色'),
        ),
    ]
